using System.Collections.Generic;
using HarmonyLib;
using UnityEngine;

namespace ProtectiveWear
{
    // Dynamic Soft Suit headgear. While the suit is worn, sealed headgear
    // assembles over the duplicant's head ONLY when they're in a dangerous
    // environment (any gas that isn't pure oxygen, vacuum, liquid, heat, or
    // radiation), MCU-style -- each part slides into place in sequence:
    //
    //   stage 0  bare head
    //   stage 1  neck collar appears, helmet dome arrives high above the head
    //   stage 2  dome slides halfway down
    //   stage 3  dome seats and seals
    //   stage 4  oxygen mask slides up from below
    //   stage 5  mask seats -- fully sealed
    //
    // One stage advances per INTERVAL, and leaving danger runs the same
    // sequence in reverse (mask releases first, then the dome lifts away).
    //
    // Every piece is drawn the same way the game draws the Atmo Suit helmet
    // and the worn Oxygen Mask: symbol overrides on the head anchors, using
    // build-only art (the dome/collar from the game's atmo_helmet_clear on
    // "snapto_neck"/"neck", the mask from the game's mask_oxygen on
    // "snapto_goggles"). The in-between "sliding" positions are our own
    // pivot-shifted copies of those builds (eva_dome_s1/s2, eva_mask_s1,
    // generated by tools/gen_protective_kanims.py) -- same art, nudged
    // relative to the anchor, so stepping through them reads as motion.
    //
    // IMPORTANT: the dupe rig ships with every snapto_* symbol HIDDEN (the
    // base minion config calls SetSymbolVisiblity(..., false) on all of them),
    // so on top of the override the anchor must be toggled visible, exactly as
    // the game does when it equips real masks/helmets.
    //
    // Runtime-added KMonoBehaviours don't get the normal Sim registration, so
    // we avoid a per-dupe component entirely: a single static set of wearers
    // is ticked from Game.SimEveryTick (below).
    public static class EVAHelmetManager
    {
        private const string DOME_TARGET = "snapto_neck";
        private const string COLLAR_TARGET = "neck";
        private const string MASK_TARGET = "snapto_goggles";
        private const int PRIORITY = 7;        // beat the worn-suit build override
        private const float INTERVAL = 0.15f;  // seconds per assembly step
        private const float ARM_DELAY = 1.5f;  // continuous danger required before assembly starts
        private const float HOT_TEMP_K = 323.15f;  // 50 C -- seal the helmet in heat
        private const float RAD_THRESHOLD = 30f;    // rads -- seal the helmet in radiation
        private const int MAX_STAGE = 5;
        // Below this fraction of the breath reserve the "suit air" fiction ends
        // and vanilla holding-breath/suffocation behaviour takes back over, so
        // dupes still panic and go find real oxygen before they drop. Kept
        // generous so they turn back with plenty of margin for the walk out.
        private const float LOW_AIR_FRACTION = 0.25f;
        // Refilling breath happens in two tiers: up to a normal dupe's lungful
        // it catches up at the full vanilla breathing rate, so the wearer is
        // mission-ready fast; above that (the suit's BREATH_BONUS reserve) it
        // backfills passively at this fraction of the normal rate.
        private const float RESERVE_REFILL_FRACTION = 0.4f;

        private static readonly HashSet<GameObject> wearers = new HashSet<GameObject>();
        // Assembly stage per wearer (see table above); absent = 0.
        private static readonly Dictionary<GameObject, int> stages =
            new Dictionary<GameObject, int>();
        // Seconds of continuous danger per wearer; assembly only starts once
        // this reaches ARM_DELAY (a brief "is this real?" beat).
        private static readonly Dictionary<GameObject, float> dwell =
            new Dictionary<GameObject, float>();
        // Wearers currently breathing from the suit ("suit air"): fully sealed
        // in unbreathable surroundings with reserve left. Consulted by the
        // CanBreath patch below; carries the replacement breath drain.
        private static readonly HashSet<GameObject> suitAir = new HashSet<GameObject>();
        private static Klei.AI.AttributeModifier suitAirDrain;
        // Wearers whose over-normal reserve is currently backfilling slowly.
        private static readonly HashSet<GameObject> slowTopUp = new HashSet<GameObject>();
        private static Klei.AI.AttributeModifier reserveTopUpDrain;
        private static float timer;

        // Wearers whose breath reserve still needs its one-time top-up. The
        // BreathMax modifier is applied by the equip system around the same
        // time as our callback, so the top-up runs on the next tick, once the
        // new max is definitely in place ("the suit comes charged with air" --
        // otherwise the breath bar drops to 1/3 the moment the suit goes on).
        private static readonly HashSet<GameObject> pendingBreath = new HashSet<GameObject>();

        private static bool symbolsTried;
        private static KAnim.Build.Symbol collarSymbol;
        private static readonly List<KAnim.Build.Symbol> domeStages = new List<KAnim.Build.Symbol>();
        private static readonly List<KAnim.Build.Symbol> maskStages = new List<KAnim.Build.Symbol>();

        private static KAnim.Build.Symbol GetSym(string animName, string symbolName)
        {
            KAnimFile anim = Assets.GetAnim((HashedString)animName);
            if (anim == null)
            {
                Debug.LogWarning("[ProtectiveWear] kanim not found: " + animName);
                return null;
            }
            KAnim.Build.Symbol s = anim.GetData().build.GetSymbol((KAnimHashedString)symbolName);
            if (s == null)
                Debug.LogWarning("[ProtectiveWear] " + animName + " has no symbol " + symbolName);
            return s;
        }

        private static void LoadSymbols()
        {
            if (symbolsTried) return;
            symbolsTried = true;

            collarSymbol = GetSym("atmo_helmet_clear_kanim", COLLAR_TARGET);
            KAnim.Build.Symbol domeFinal = GetSym("atmo_helmet_clear_kanim", DOME_TARGET);
            // Nozzle-free mask (just the cup, hose/puff stripped) -- see
            // gen_protective_kanims.strip_nozzle. Falls back to the vanilla mask
            // if the generated kanim is somehow missing.
            KAnim.Build.Symbol maskFinal = GetSym("eva_mask_kanim", MASK_TARGET)
                                            ?? GetSym("mask_oxygen_kanim", MASK_TARGET);

            // Sliding in-betweens; if a generated kanim is missing, fall back
            // to the seated art so the sequence degrades to a snap, not a hole.
            KAnim.Build.Symbol s1 = GetSym("eva_dome_s1_kanim", DOME_TARGET);
            KAnim.Build.Symbol s2 = GetSym("eva_dome_s2_kanim", DOME_TARGET);
            domeStages.Add(s1 != null ? s1 : domeFinal);
            domeStages.Add(s2 != null ? s2 : domeFinal);
            domeStages.Add(domeFinal);

            KAnim.Build.Symbol m1 = GetSym("eva_mask_s1_kanim", MASK_TARGET);
            maskStages.Add(m1 != null ? m1 : maskFinal);
            maskStages.Add(maskFinal);
        }

        private static KAnim.Build.Symbol DomeFor(int stage)
        {
            if (stage <= 0) return null;
            return domeStages[Mathf.Min(stage, 3) - 1];
        }

        private static KAnim.Build.Symbol MaskFor(int stage)
        {
            if (stage <= 3) return null;
            return maskStages[Mathf.Min(stage, 5) - 4];
        }

        public static bool IsWearer(GameObject go)
        {
            return go != null && wearers.Contains(go);
        }

        public static void OnEquip(Equippable eq)
        {
            GameObject w = GetWearer(eq);
            Debug.Log("[ProtectiveWear] Soft Suit equipped, wearer=" + (w != null ? w.name : "NULL"));
            if (w == null) return;
            wearers.Add(w);
            pendingBreath.Add(w);
            // Sealed suit: airborne germs can't be inhaled, same flag the Atmo
            // Suit and Oxygen Mask set on their wearer.
            w.AddTag(GameTags.HasAirtightSuit);
        }

        public static void OnUnequip(Equippable eq)
        {
            GameObject w = GetWearer(eq);
            if (w == null) return;
            wearers.Remove(w);
            pendingBreath.Remove(w);
            dwell.Remove(w);
            SetSuitAir(w, false);
            SetSlowTopUp(w, false);
            w.RemoveTag(GameTags.HasAirtightSuit);
            SetStage(w, 0);   // suit off = everything off at once
        }

        public static bool IsSuitAir(GameObject go)
        {
            return go != null && suitAir.Contains(go);
        }

        public static void Tick(float dt)
        {
            if (wearers.Count == 0) return;
            timer += dt;
            if (timer < INTERVAL) return;
            timer = 0f;
            foreach (GameObject w in new List<GameObject>(wearers))
            {
                if (w == null)
                {
                    wearers.Remove(w);
                    pendingBreath.Remove(w);
                    dwell.Remove(w);
                    suitAir.Remove(w);
                    slowTopUp.Remove(w);
                    continue;
                }
                if (pendingBreath.Remove(w))
                {
                    Klei.AI.AmountInstance breath = Db.Get().Amounts.Breath.Lookup(w);
                    if (breath != null) breath.value = breath.GetMax();
                }

                // Keep the airtight seal asserted for as long as the suit is
                // worn. The tag is set on equip, but a facade refresh or a
                // missed equip on save-load could drop it, leaving bionic dupes
                // exposed to the water shock -- re-adding it here every tick
                // makes the immunity reliable.
                if (!w.HasTag(GameTags.HasAirtightSuit))
                    w.AddTag(GameTags.HasAirtightSuit);

                // A real suit (Atmo/Lead/Jet) worn on top already seals the
                // dupe, so don't also assemble the Soft Suit helmet/mask -- it
                // would be redundant and clash with the suit's own headgear.
                if (SuitInteraction.WearsRealSuit(w))
                {
                    RetractForRealSuit(w);
                    SetSuitAir(w, false);
                    SetSlowTopUp(w, false);
                    dwell[w] = 0f;
                    continue;
                }

                int cur;
                stages.TryGetValue(w, out cur);
                bool danger = IsDangerous(w);

                // Arm the helmet only after ARM_DELAY of continuous danger; a
                // partially-assembled helmet resumes immediately.
                float t;
                dwell.TryGetValue(w, out t);
                dwell[w] = danger ? t + INTERVAL : 0f;
                int want;
                if (danger)
                    want = (cur > 0 || dwell[w] >= ARM_DELAY) ? cur + 1 : cur;
                else
                    want = cur - 1;
                int stage = Mathf.Clamp(want, 0, MAX_STAGE);
                SetStage(w, stage);

                // Fully sealed in unbreathable surroundings = breathing from
                // the suit: no held breath, but the reserve drains at the
                // vanilla holding-breath rate until it runs low.
                Klei.AI.AmountInstance breathAmt = Db.Get().Amounts.Breath.Lookup(w);
                float frac = breathAmt != null && breathAmt.GetMax() > 0f
                    ? breathAmt.value / breathAmt.GetMax() : 0f;
                SetSuitAir(w, stage == MAX_STAGE && !IsBreathable(w) && frac > LOW_AIR_FRACTION);

                // Two-tier refill: while in oxygen, catch up to a normal dupe's
                // lungful at full speed, then slow the fill for the reserve above
                // it. "Normal" = the current max minus the suit's bonus.
                float normalBreath = breathAmt != null
                    ? Mathf.Max(0f, breathAmt.GetMax() - EVASuitConfig.BREATH_BONUS) : 0f;
                bool toppingReserve = breathAmt != null && IsBreathable(w)
                    && breathAmt.value < breathAmt.GetMax() && breathAmt.value >= normalBreath;
                SetSlowTopUp(w, toppingReserve);
            }
        }

        private static void SetSuitAir(GameObject dupe, bool on)
        {
            if (dupe == null || on == suitAir.Contains(dupe)) return;
            if (suitAirDrain == null)
            {
                // While on suit air the state machine sits in its "breathing"
                // state, whose +BREATH_RATE refill is gated on the same
                // CanBreath() we patch -- so cancel that refill AND drain at
                // the vanilla rate: net -BREATH_RATE, exactly holding-breath
                // depletion, just without the held breath.
                float rate = TUNING.DUPLICANTSTATS.STANDARD.Breath.BREATH_RATE;
                suitAirDrain = new Klei.AI.AttributeModifier(
                    Db.Get().Amounts.Breath.deltaAttribute.Id, -2f * rate,
                    "Soft Suit air supply", false, false, false);
            }
            Klei.AI.Attributes attrs = Klei.AI.ModifiersExtensions.GetAttributes(dupe);
            if (attrs == null) return;
            if (on)
            {
                suitAir.Add(dupe);
                attrs.Add(suitAirDrain);
            }
            else
            {
                suitAir.Remove(dupe);
                attrs.Remove(suitAirDrain);
            }
        }

        // Slow the breathing-state refill while topping up the over-normal
        // reserve, so the bonus air backfills at RESERVE_REFILL_FRACTION speed.
        private static void SetSlowTopUp(GameObject dupe, bool on)
        {
            if (dupe == null || on == slowTopUp.Contains(dupe)) return;
            if (reserveTopUpDrain == null)
            {
                // Breathing adds +BREATH_RATE; subtract most of it so the net
                // refill above normal is RESERVE_REFILL_FRACTION * BREATH_RATE.
                float rate = TUNING.DUPLICANTSTATS.STANDARD.Breath.BREATH_RATE;
                reserveTopUpDrain = new Klei.AI.AttributeModifier(
                    Db.Get().Amounts.Breath.deltaAttribute.Id,
                    -(1f - RESERVE_REFILL_FRACTION) * rate,
                    "Soft Suit reserve top-up", false, false, false);
            }
            Klei.AI.Attributes attrs = Klei.AI.ModifiersExtensions.GetAttributes(dupe);
            if (attrs == null) return;
            if (on)
            {
                slowTopUp.Add(dupe);
                attrs.Add(reserveTopUpDrain);
            }
            else
            {
                slowTopUp.Remove(dupe);
                attrs.Remove(reserveTopUpDrain);
            }
        }

        // A real suit (Atmo/Lead/Jet) is worn on top: drop OUR headgear so the
        // suit's own helmet shows, but keep the mask off. The Atmo Suit draws
        // its dome on snapto_neck, so we must leave that symbol VISIBLE after
        // removing our override (SetStage(0) force-hid it, which killed the
        // suit's helmet too). snapto_goggles has no suit art, so hide it.
        private static void RetractForRealSuit(GameObject dupe)
        {
            int cur;
            if (!stages.TryGetValue(dupe, out cur) || cur == 0) return;
            SymbolOverrideController soc = dupe.GetComponent<SymbolOverrideController>();
            KBatchedAnimController kbac = dupe.GetComponent<KBatchedAnimController>();
            if (soc == null || kbac == null) { stages.Remove(dupe); return; }
            SymbolOverrideControllerUtil.TryRemoveSymbolOverride(soc, (HashedString)COLLAR_TARGET, PRIORITY);
            SymbolOverrideControllerUtil.TryRemoveSymbolOverride(soc, (HashedString)DOME_TARGET, PRIORITY);
            kbac.SetSymbolVisiblity((KAnimHashedString)DOME_TARGET, true);   // let the suit's dome show
            SymbolOverrideControllerUtil.TryRemoveSymbolOverride(soc, (HashedString)MASK_TARGET, PRIORITY);
            kbac.SetSymbolVisiblity((KAnimHashedString)MASK_TARGET, false);  // suit has no mask symbol
            stages.Remove(dupe);
        }

        private static void SetStage(GameObject dupe, int stage)
        {
            if (dupe == null) return;
            int cur;
            stages.TryGetValue(dupe, out cur);
            if (stage == cur) return;
            SymbolOverrideController soc = dupe.GetComponent<SymbolOverrideController>();
            KBatchedAnimController kbac = dupe.GetComponent<KBatchedAnimController>();
            if (soc == null || kbac == null) return;
            LoadSymbols();

            // Collar: present through the whole assembled range.
            if (stage >= 1 && cur < 1 && collarSymbol != null)
            {
                soc.AddSymbolOverride((HashedString)COLLAR_TARGET, collarSymbol, PRIORITY);
            }
            else if (stage < 1 && cur >= 1)
            {
                SymbolOverrideControllerUtil.TryRemoveSymbolOverride(soc, (HashedString)COLLAR_TARGET, PRIORITY);
            }

            SwapPart(soc, kbac, DOME_TARGET, DomeFor(cur), DomeFor(stage));
            SwapPart(soc, kbac, MASK_TARGET, MaskFor(cur), MaskFor(stage));

            if (stage == 0) stages.Remove(dupe);
            else stages[dupe] = stage;
        }

        private static void SwapPart(SymbolOverrideController soc, KBatchedAnimController kbac,
                                     string target, KAnim.Build.Symbol have, KAnim.Build.Symbol want)
        {
            if (want == have) return;
            SymbolOverrideControllerUtil.TryRemoveSymbolOverride(soc, (HashedString)target, PRIORITY);
            if (want != null)
            {
                soc.AddSymbolOverride((HashedString)target, want, PRIORITY);
                if (have == null) kbac.SetSymbolVisiblity((KAnimHashedString)target, true);
            }
            else
            {
                kbac.SetSymbolVisiblity((KAnimHashedString)target, false);
            }
        }

        // Pure Oxygen in the dupe's cell (the only thing that doesn't seal).
        private static bool IsBreathable(GameObject dupe)
        {
            int cell = Grid.PosToCell(dupe);
            if (!Grid.IsValidCell(cell)) return false;
            Element e = Grid.Element[cell];
            return e != null && e.id == SimHashes.Oxygen && Grid.Mass[cell] > 0.1f;
        }

        private static bool IsDangerous(GameObject dupe)
        {
            int cell = Grid.PosToCell(dupe);
            if (!Grid.IsValidCell(cell)) return false;

            // Seal in anything that isn't pure Oxygen: polluted oxygen, other
            // gases, vacuum, or a liquid the dupe is standing in.
            if (!IsBreathable(dupe)) return true;

            // Dangerous heat.
            if (Grid.Temperature[cell] > HOT_TEMP_K) return true;

            // Radiation (the cell already passed IsValidCell).
            if (Grid.Radiation[cell] > RAD_THRESHOLD) return true;

            return false;
        }

        internal static GameObject GetWearer(Equippable eq)
        {
            IAssignableIdentity assignee = eq != null ? eq.assignee : null;
            if (assignee == null) return null;

            // The assignee can be the minion itself or its assignables proxy,
            // depending on how the equip happened; handle both.
            MinionIdentity mi = assignee as MinionIdentity;
            if (mi != null) return mi.gameObject;

            MinionAssignablesProxy proxy = assignee as MinionAssignablesProxy;
            if (proxy == null)
            {
                Ownables owner = assignee.GetSoleOwner();
                if (owner != null) proxy = owner.GetComponent<MinionAssignablesProxy>();
            }
            return proxy != null ? proxy.GetTargetGameObject() : null;
        }
    }

    // Drive the helmet check off the sim clock (only ticks while unpaused).
    [HarmonyPatch(typeof(Game), "SimEveryTick")]
    public static class Game_SimEveryTick_Helmet
    {
        public static void Postfix(float dt)
        {
            EVAHelmetManager.Tick(dt);
        }
    }

    // While sealed with reserve left, the dupe breathes suit air: CanBreath()
    // is what flips the SuffocationMonitor into its holding-breath state (the
    // puffed-cheeks expression, the "Holding Breath" status, the panic), so
    // reporting true keeps the dupe acting completely normal. The matching
    // suitAirDrain modifier (managed in Tick) keeps the reserve depleting at
    // the vanilla rate, and below LOW_AIR_FRACTION the override stops --
    // vanilla behaviour returns and the dupe goes looking for real air.
    [HarmonyPatch(typeof(SuffocationMonitor.Instance), "CanBreath")]
    public static class SuffocationMonitor_CanBreath_SoftSuit
    {
        public static void Postfix(SuffocationMonitor.Instance __instance, ref bool __result)
        {
            if (!__result && EVAHelmetManager.IsSuitAir(__instance.master.gameObject))
                __result = true;
        }
    }

    // Deterministic backstop for the suit's effect immunities: the def's
    // EffectImmunites list should already register these via Equippable
    // .OnEquip, but the first in-game test still saw Sopping Wet applied, so
    // gate the immunity check itself on being a Soft Suit wearer too.
    [HarmonyPatch(typeof(Klei.AI.Effects), "HasImmunityTo")]
    public static class Effects_HasImmunityTo_SoftSuit
    {
        private static readonly HashSet<string> BLOCKED = new HashSet<string>
        {
            "SoakingWet", "WetFeet", "ColdAir", "WarmAir", "MinorIrritation", "MajorIrritation", "PoppedEarDrums",
        };

        public static void Postfix(Klei.AI.Effects __instance, Klei.AI.Effect effect, ref bool __result)
        {
            if (!__result && effect != null && BLOCKED.Contains(effect.Id) &&
                EVAHelmetManager.IsWearer(__instance.gameObject))
                __result = true;
        }
    }
}
