using UnityEngine;

namespace SnazzySwimwear
{
    // Snazzy Rubber Boots: the vanilla Rubber Boots with a gold sequin finish
    // and +15 room decor. Same delegation approach as the swimwear -- keep the
    // feet-protection tag and wet-feet/slip immunities from RubberBootsConfig,
    // swap the item kanim, and add decor. Vanilla boots have no worn-body
    // kanim, so (like vanilla) only the item art changes.
    public class SnazzyRubberBootsConfig : IEquipmentConfig
    {
        public const string ID = "SnazzyRubberBoots";
        public const float DECOR = 15f;

        private readonly RubberBootsConfig vanilla = new RubberBootsConfig();

        public EquipmentDef CreateEquipmentDef()
        {
            EquipmentDef def = vanilla.CreateEquipmentDef();
            def.Id = ID;
            def.Anim = Assets.GetAnim((HashedString)"snazzy_rubber_boots_item_kanim");
            // Worn-feet art (vanilla footwear has none): dresses both dupes'
            // and the Mannequin's feet. Generated by tools/gen_worn_feet_kanims.py.
            def.BuildOverride = Assets.GetAnim((HashedString)"body_snazzy_rubber_boots_kanim");
            // Layer at the normal clothing priority (4). Vanilla boots have no
            // worn art, so this field is otherwise left at a value that can
            // outrank a suit's body override (6) -- which drew our boots on top
            // of an Atmo Suit's feet. Pinned to 4, any suit correctly wins.
            def.BuildOverridePriority = 4;

            System.Action<Equippable> baseEquip = def.OnEquipCallBack;
            System.Action<Equippable> baseUnequip = def.OnUnequipCallBack;
            def.OnEquipCallBack = (Equippable eq) =>
            {
                baseEquip?.Invoke(eq);
                SnazzyDecor.Add(eq, DECOR, "Snazzy Rubber Boots");
            };
            def.OnUnequipCallBack = (Equippable eq) =>
            {
                SnazzyDecor.Remove(eq);
                baseUnequip?.Invoke(eq);
            };
            return def;
        }

        public void DoPostConfigure(GameObject go)
        {
            vanilla.DoPostConfigure(go);
        }

        // Obsolete interface member; no DLC restriction of our own.
        public string[] GetDlcIds()
        {
            return null;
        }
    }
}
