using HarmonyLib;
using UnityEngine;

namespace ProtectiveWear
{
    // While the Refashionator works on one of our recipes, swap the garment
    // shown on its table -- the station art's "object" symbol, by default a
    // yellow-and-black snazzy suit being stretched -- for a rainbow-tinted
    // copy of the same art (refashion_rainbow_kanim, generated by
    // tools/gen_protective_kanims.py), so the animation plays unchanged but
    // multicoloured. The override is removed when work stops, restoring the
    // vanilla art for the vanilla recipes.
    public static class StationDisplay
    {
        private const string STATION_ID = "ClothingAlterationStation";
        private const string GARMENT_SYMBOL = "object";
        private const string RAINBOW_ANIM = "refashion_rainbow_kanim";
        private const int PRIORITY = 2;

        private static string ResultAnimFor(Tag result)
        {
            if (result == (Tag)EVASuitConfig.ID) return RAINBOW_ANIM;
            if (result == (Tag)UpgradedWarmCoatConfig.ID) return RAINBOW_ANIM;
            return null;
        }

        public static void Refresh(ComplexFabricatorWorkable workable, bool working)
        {
            if (workable == null) return;
            KPrefabID prefab = workable.GetComponent<KPrefabID>();
            if (prefab == null || prefab.PrefabTag != (Tag)STATION_ID) return;
            SymbolOverrideController soc = workable.GetComponent<SymbolOverrideController>();
            if (soc == null) return;

            string animName = null;
            if (working)
            {
                ComplexRecipe order = workable.CurrentWorkingOrder;
                if (order != null && order.results != null && order.results.Length > 0)
                    animName = ResultAnimFor(order.results[0].material);
            }

            if (animName == null)
            {
                SymbolOverrideControllerUtil.TryRemoveSymbolOverride(soc, (HashedString)GARMENT_SYMBOL, PRIORITY);
                return;
            }

            KAnimFile anim = Assets.GetAnim((HashedString)animName);
            if (anim == null) return;
            KAnim.Build.Symbol sym = anim.GetData().build.GetSymbol((KAnimHashedString)GARMENT_SYMBOL);
            if (sym != null)
                soc.AddSymbolOverride((HashedString)GARMENT_SYMBOL, sym, PRIORITY);
        }
    }

    // The station has no SymbolOverrideController of its own; add one to the
    // prefab so the per-recipe garment swap has something to talk to.
    [HarmonyPatch(typeof(ClothingAlterationStationConfig), "DoPostConfigureComplete")]
    public static class ClothingAlterationStation_AddSOC
    {
        public static void Postfix(GameObject go)
        {
            SymbolOverrideControllerUtil.AddToPrefab(go);
        }
    }

    [HarmonyPatch(typeof(ComplexFabricatorWorkable), "OnStartWork")]
    public static class ComplexFabricatorWorkable_OnStartWork_Display
    {
        public static void Postfix(ComplexFabricatorWorkable __instance)
        {
            StationDisplay.Refresh(__instance, true);
        }
    }

    [HarmonyPatch(typeof(ComplexFabricatorWorkable), "OnStopWork")]
    public static class ComplexFabricatorWorkable_OnStopWork_Display
    {
        public static void Postfix(ComplexFabricatorWorkable __instance)
        {
            StationDisplay.Refresh(__instance, false);
        }
    }
}
