using TUNING;
using UnityEngine;
using BUILDINGS = TUNING.BUILDINGS;

namespace MagpieExtensionRonivans
{
    // Wraps Ronivans' HPARailBridgeTileConfig (Heavy-Duty Joint Plate). The base
    // config is a tile-foundation building (IsFoundation = true, TileLayer set,
    // etc.), so after CreateBuildingDef we MUST also call CreateFoundationTileDef
    // to populate those fields -- otherwise placement validation fails and ONI
    // dumps the construction material as copper ore on the ground.
    public class HPARailBridgeTile2Config : IBuildingConfig
    {
        public const string ID = "HPARailBridgeTile2";
        public const string BASE_TYPE = "RonivansLegacy_ChemicalProcessing.Content.Defs.Buildings.HighPressureApplications.HighCapacityLogisticRails.HPARailBridgeTileConfig";
        private static readonly IBuildingConfig BaseConfig = RonivansHelpers.CreateBaseConfig(BASE_TYPE);

        public override BuildingDef CreateBuildingDef()
        {
            if (BaseConfig == null) return RonivansHelpers.CreateMissingDependencyDef(ID, 4, "hpa_rail_tile_bridge4_kanim");
            BuildingDef baseDef = BaseConfig.CreateBuildingDef();
            // hpa_rail_tile_bridge4_kanim is our own 4-cell-wide recomposition of
            // Ronivans' art, generated by tools/gen_extended_kanims.py and shipped
            // in anim/magpie_extended_anims/. Using a real kanim lets ONI place and
            // rotate the visual natively -- no runtime child renderers needed.
            BuildingDef def = BuildingTemplates.CreateBuildingDef(
                ID, 4, 1, "hpa_rail_tile_bridge4_kanim", 30, 30f,
                BUILDINGS.CONSTRUCTION_MASS_KG.TIER4, MATERIALS.ALL_METALS, 1600f,
                BuildLocationRule.Tile, BUILDINGS.DECOR.NONE, NOISE_POLLUTION.NONE);
            // Foundation-tile setup BEFORE our copies, so our specific overrides
            // from baseDef take precedence over CreateFoundationTileDef defaults
            // where they differ.
            BuildingTemplates.CreateFoundationTileDef(def);
            def.TileLayer         = baseDef.TileLayer;
            def.ReplacementLayer  = baseDef.ReplacementLayer;
            def.IsFoundation      = baseDef.IsFoundation;
            def.ObjectLayer       = baseDef.ObjectLayer;
            def.SceneLayer        = baseDef.SceneLayer;
            def.ForegroundLayer   = baseDef.ForegroundLayer;
            def.InputConduitType  = baseDef.InputConduitType;
            def.OutputConduitType = baseDef.OutputConduitType;
            def.ViewMode          = baseDef.ViewMode;
            def.AudioCategory     = baseDef.AudioCategory;
            def.AudioSize         = baseDef.AudioSize;
            def.ThermalConductivity = baseDef.ThermalConductivity;
            def.UseStructureTemperature = baseDef.UseStructureTemperature;
            def.Floodable         = false;
            def.Entombable        = false;
            def.Overheatable      = false;
            def.BaseTimeUntilRepair = -1f;
            // R360 = full 4-orientation cycle (left/up/right/down). R90 in ONI
            // is only a 2-state toggle (horizontal/vertical), which limited the
            // joint plate to input-facing-left and input-facing-up only.
            def.PermittedRotations = PermittedRotations.R360;
            // 4-wide: cells span x in [-1, 0, 1, 2].
            def.UtilityInputOffset  = new CellOffset(-1, 0);
            def.UtilityOutputOffset = new CellOffset(2, 0);
            GeneratedBuildings.RegisterWithOverlay(OverlayScreen.SolidConveyorIDs, ID);
            return def;
        }

        public override void ConfigureBuildingTemplate(GameObject go, Tag prefab_tag) { if (BaseConfig != null) BaseConfig.ConfigureBuildingTemplate(go, prefab_tag); }
        public override void DoPostConfigurePreview(BuildingDef def, GameObject go)
        {
            if (BaseConfig != null) BaseConfig.DoPostConfigurePreview(def, go);
        }
        public override void DoPostConfigureUnderConstruction(GameObject go)
        {
            if (BaseConfig != null) BaseConfig.DoPostConfigureUnderConstruction(go);
        }
        public override void DoPostConfigureComplete(GameObject go)
        {
            if (BaseConfig != null) BaseConfig.DoPostConfigureComplete(go);
        }
    }
}
