using TUNING;
using UnityEngine;
using BUILDINGS = TUNING.BUILDINGS;

namespace MagpieExtensionRonivans
{
    public class HPGasBridge3Config : IBuildingConfig
    {
        public const string ID = "HPGasBridge3";
        public const string BASE_TYPE = "High_Pressure_Applications.BuildingConfigs.HighPressureGasConduitBridgeConfig";
        private static readonly IBuildingConfig BaseConfig = RonivansHelpers.CreateBaseConfig(BASE_TYPE);

        public override BuildingDef CreateBuildingDef()
        {
            if (BaseConfig == null) return RonivansHelpers.CreateMissingDependencyDef(ID, 5, "pressure_gas_bridge5_kanim");
            BuildingDef baseDef = BaseConfig.CreateBuildingDef();
            // 5-wide variant of Ronivans' High Pressure Gas Bridge; kanim
            // generated by tools/gen_extended_kanims.py (stretch baked in).
            BuildingDef def = BuildingTemplates.CreateBuildingDef(
                ID, 5, 1, "pressure_gas_bridge5_kanim", 30, 30f,
                baseDef.Mass, baseDef.MaterialCategory, 1600f,
                BuildLocationRule.Conduit, BUILDINGS.DECOR.NONE, NOISE_POLLUTION.NONE);
            def.ObjectLayer       = baseDef.ObjectLayer;
            def.SceneLayer        = baseDef.SceneLayer;
            def.InputConduitType  = ConduitType.Gas;
            def.OutputConduitType = ConduitType.Gas;
            def.ViewMode          = baseDef.ViewMode;
            def.AudioCategory     = baseDef.AudioCategory;
            def.AudioSize         = baseDef.AudioSize;
            def.Floodable         = false;
            def.Entombable        = false;
            def.Overheatable      = baseDef.Overheatable;
            def.BaseTimeUntilRepair = -1f;
            def.PermittedRotations = PermittedRotations.R360;
            // 5-wide centered: cells [-2, -1, 0, 1, 2]. Ports at leftmost/rightmost.
            def.UtilityInputOffset  = new CellOffset(-2, 0);
            def.UtilityOutputOffset = new CellOffset(2, 0);
            GeneratedBuildings.RegisterWithOverlay(OverlayScreen.GasVentIDs, ID);
            return def;
        }

        public override void ConfigureBuildingTemplate(GameObject go, Tag prefab_tag) { if (BaseConfig != null) BaseConfig.ConfigureBuildingTemplate(go, prefab_tag); }
        public override void DoPostConfigurePreview(BuildingDef def, GameObject go) { if (BaseConfig != null) BaseConfig.DoPostConfigurePreview(def, go); }
        public override void DoPostConfigureUnderConstruction(GameObject go) { if (BaseConfig != null) BaseConfig.DoPostConfigureUnderConstruction(go); }
        public override void DoPostConfigureComplete(GameObject go) { if (BaseConfig != null) BaseConfig.DoPostConfigureComplete(go); }
    }
}
